name: Validate Translations

on:
  pull_request:
    paths:
      - "**/*.po"

jobs:
  compile-po:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Validate .po files
        run: |
          ./bin/i18n compile
